-- MySQL
-- 코드를 입력하세요
SELECT a.CART_ID
FROM (SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = "Milk"
    GROUP BY CART_ID
    ) a,
    (SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = "Yogurt"
    GROUP BY CART_ID
    ) b
WHERE a.CART_ID = b.CART_ID
ORDER BY CART_ID ASC;